services:
  recomendationsservice:
    image: recomendationsservice
    build:
      context: .
      dockerfile: RecomendationsService/Dockerfile
  coreservice:
    image: petshop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
