services:
  coreservice:
    image: petshop
    build:
      context: .
      dockerfile: PetShop/Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
      - app-network

  recomendationsservice:
    image: recomendationsservice
    build:
      context: .
      dockerfile: RecomendationsService/Dockerfile
    container_name: recoservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:25000
    ports:
      - "25000:25000"
    networks:
      - app-network
      
  proxy:
    image: proxy
    build: Proxy/
    ports:
      - 80:80
        
networks:
  app-network:
    driver: bridge